mongodb:
  # mongodb connection uri
  uri: ""
  # mongodb database name and collection name to use
  db_name: "the_oracle_n"
  collection_name: "server_health_data"

# server name - DO NOT CHANGE ONCE SET
server_name: ""

# Pterodactyl data
petro:
  base_url: ""

  # DON'T CHANGE THE SERVER_ID EVER
  server_id: ""

  api_key: ""